"use client";

import { useEffect, useState } from "react";
import { RawData, ViewMode } from "./types";
import dynamic from "next/dynamic";
import Legend from "./components/Legend";

const Treemap = dynamic(() => import("./components/Treemap"), { ssr: false });

const MODES: { id: ViewMode; label: string }[] = [
  { id: "ai_exposure", label: "AI Exposure" },
  { id: "growth", label: "Job Growth" },
  { id: "wage", label: "Median Wage" },
  { id: "education", label: "Education" },
];

export default function Home() {
  const [data, setData] = useState<RawData | null>(null);
  const [mode, setMode] = useState<ViewMode>("ai_exposure");
  const [totalJobs, setTotalJobs] = useState(0);

  useEffect(() => {
    fetch("/data.json")
      .then((r) => r.json())
      .then((d: RawData) => {
        setData(d);
        const total = d.children.flatMap((g) => g.children).reduce((s, o) => s + o.employment, 0);
        setTotalJobs(total);
      });
  }, []);

  const activeMode = MODES.find((m) => m.id === mode)!;

  return (
    /* Desktop: fixed full-viewport, no scroll. Mobile: scrollable page. */
    <div className="flex flex-col bg-[#0a0a0f] text-white md:h-screen md:overflow-hidden">

      {/* Header */}
      <header className="flex-shrink-0 px-4 md:px-5 pt-4 md:pt-5 pb-3">
        <div className="flex items-center justify-between gap-2 mb-1">
          <div className="flex items-center gap-2">
            <div className="w-5 h-5 rounded-sm bg-red-500 flex items-center justify-center flex-shrink-0">
              <span className="text-white font-bold text-xs leading-none">CA</span>
            </div>
            <h1 className="text-base md:text-lg font-bold tracking-tight leading-tight">
              Canadian Job Market
              <span className="text-white/40 font-normal ml-1.5 text-sm hidden sm:inline">Visualizer</span>
            </h1>
          </div>
        </div>

        <p className="text-white/40 text-xs mb-3">
          {data
            ? `${data.children.flatMap((g) => g.children).length} occupations · ${(totalJobs / 1e6).toFixed(1)}M jobs · ${activeMode.label}. Tap any tile for details.`
            : "Loading…"}
        </p>

        {/* Mode toggle — horizontally scrollable on mobile */}
        <div className="overflow-x-auto pb-1 -mx-4 px-4 md:mx-0 md:px-0">
          <div className="flex gap-1 bg-white/5 rounded-lg p-1 border border-white/10 w-max md:w-auto">
            {MODES.map((m) => (
              <button
                key={m.id}
                onClick={() => setMode(m.id)}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all whitespace-nowrap ${
                  mode === m.id
                    ? "bg-white text-black shadow-sm"
                    : "text-white/60 active:bg-white/10 md:hover:text-white md:hover:bg-white/10"
                }`}
              >
                {m.label}
              </button>
            ))}
          </div>
        </div>

        {/* Legend */}
        <div className="mt-2.5">
          <Legend mode={mode} />
        </div>
      </header>

      {/* Treemap — fills remaining viewport on desktop, tall fixed height on mobile */}
      <main className="flex-1 md:min-h-0 px-3 md:px-5 pb-4">
        <div
          className="w-full rounded-xl overflow-hidden border border-white/5"
          style={{ height: "clamp(480px, 160vw, 9999px)" }}
        >
          <div className="w-full h-full md:h-full" style={{ height: "inherit" }}>
            {data ? (
              <Treemap data={data} mode={mode} />
            ) : (
              <div className="w-full h-full flex items-center justify-center text-white/20 text-sm">
                Loading…
              </div>
            )}
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="flex-shrink-0 px-4 md:px-5 pb-4 md:pb-3 flex flex-wrap gap-x-3 gap-y-1 text-xs text-white/20">
        <span>Data: Statistics Canada NOC 2021 · Labour Force Survey 2023</span>
        <span className="hidden md:inline">·</span>
        <span>AI scores generated by Claude · For research purposes only</span>
      </footer>
    </div>
  );
}
