"use client";

import { useEffect, useState } from "react";
import { RawData, ViewMode } from "./types";
import dynamic from "next/dynamic";
import Legend from "./components/Legend";

const Treemap = dynamic(() => import("./components/Treemap"), { ssr: false });

const MODES: { id: ViewMode; label: string; desc: string }[] = [
  { id: "ai_exposure", label: "AI Exposure", desc: "How exposed each occupation is to AI displacement (1–10)" },
  { id: "growth", label: "Job Growth", desc: "Statistics Canada projected employment growth outlook" },
  { id: "wage", label: "Median Wage", desc: "Median annual wage in Canadian dollars" },
  { id: "education", label: "Education", desc: "Typical education level required to enter the occupation" },
];

export default function Home() {
  const [data, setData] = useState<RawData | null>(null);
  const [mode, setMode] = useState<ViewMode>("ai_exposure");
  const [totalJobs, setTotalJobs] = useState(0);

  useEffect(() => {
    fetch("/data.json")
      .then((r) => r.json())
      .then((d: RawData) => {
        setData(d);
        const total = d.children.flatMap((g) => g.children).reduce((s, o) => s + o.employment, 0);
        setTotalJobs(total);
      });
  }, []);

  const activeMode = MODES.find((m) => m.id === mode)!;

  return (
    <div className="flex flex-col h-screen bg-[#0a0a0f] text-white overflow-hidden">
      {/* Header */}
      <header className="flex-shrink-0 px-5 pt-5 pb-3">
        <div className="flex flex-col md:flex-row md:items-end justify-between gap-3">
          <div>
            <div className="flex items-center gap-2 mb-0.5">
              <div className="w-5 h-5 rounded-sm bg-red-500 flex items-center justify-center">
                <span className="text-white font-bold text-xs leading-none">CA</span>
              </div>
              <h1 className="text-lg font-bold tracking-tight">
                Canadian Job Market
                <span className="text-white/40 font-normal ml-2 text-sm">Visualizer</span>
              </h1>
            </div>
            <p className="text-white/40 text-xs mt-1 max-w-lg">
              {data
                ? `${data.children.flatMap((g) => g.children).length} occupations · ${(totalJobs / 1e6).toFixed(1)}M jobs · Colour by ${activeMode.label.toLowerCase()}. Hover any tile for details.`
                : "Loading occupations…"}
            </p>
          </div>

          {/* Mode toggle */}
          <div className="flex gap-1 bg-white/5 rounded-lg p-1 border border-white/10">
            {MODES.map((m) => (
              <button
                key={m.id}
                onClick={() => setMode(m.id)}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                  mode === m.id
                    ? "bg-white text-black shadow-sm"
                    : "text-white/60 hover:text-white hover:bg-white/10"
                }`}
              >
                {m.label}
              </button>
            ))}
          </div>
        </div>

        {/* Legend */}
        <div className="mt-3">
          <Legend mode={mode} />
        </div>
      </header>

      {/* Treemap */}
      <main className="flex-1 min-h-0 px-5 pb-4">
        <div className="w-full h-full rounded-xl overflow-hidden border border-white/5">
          {data ? (
            <Treemap data={data} mode={mode} />
          ) : (
            <div className="w-full h-full flex items-center justify-center text-white/20 text-sm">
              Loading…
            </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="flex-shrink-0 px-5 pb-3 flex items-center gap-4 text-xs text-white/25">
        <span>Data: Statistics Canada NOC 2021 · Labour Force Survey 2023</span>
        <span>·</span>
        <span>AI scores generated by Claude · For research purposes only</span>
      </footer>
    </div>
  );
}
